[build]
builder = "nixpacks"
buildCommand = "php artisan config:clear && php artisan cache:clear && npm install && npm run build"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never" 