[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && composer install"

[deploy]
startCommand = """
php artisan migrate --force && \
php artisan serve --host=0.0.0.0 --port=$PORT
"""
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never"
