[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build && composer install --optimize-autoloader --no-dev"

[deploy]
startCommand = "cp .env.example .env && php artisan key:generate --force && php artisan config:clear && php artisan cache:clear && php artisan route:clear && php artisan view:clear && php artisan optimize:clear && php artisan db:monitor --timeout=60 && php artisan migrate:fresh --force && php artisan serve --host=0.0.0.0 --port=$PORT"