[build]
builder = "nixpacks"


[deploy]
startCommand = "php artisan serve --host 0.0.0.0 --port $PORT & npm run build && npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PHP_VERSION = "8.2"
NODE_VERSION = "20"

# Frontend build configuration
[frontend]
buildCommand = "npm run build"
outputDirectory = "dist"

# Database configuration (if using MySQL)
[database]
service = "mysql"
version = "8.0"

# Environment variables
[env.production]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"

# Nginx configuration (optional)
[services.nginx]
image = "nginx:latest"
ports = ["80"]
volumes = [
    "./nginx.conf:/etc/nginx/nginx.conf"
]

# Additional Railway-specific configurations
[railway]
projectName = "laravel-vue-project"
region = "us-west"