[build]
builder = "nixpacks"
buildCommand = """
    composer install --optimize-autoloader --no-dev && 
    npm install && 
    npm run build && 
    php artisan config:cache && 
    php artisan route:cache && 
    php artisan view:cache && 
    php artisan storage:link
"""

[deploy]
startCommand = ""
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never" 