[build]
builder = "nixpacks"
buildCommand = """
    # Update and install system dependencies
    apt-get update && \
    apt-get install -y curl gnupg && \
    
    # Install Node.js
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get install -y nodejs && \
    
    # Install PHP extensions
    apt-get install -y php-fpm php-mysql php-xml php-curl && \
    
    # Install Composer dependencies
    composer install --no-dev --optimize-autoloader && \
    
    # Install and build frontend
    npm ci && \
    npm run build && \
    
    # Laravel commands (skip database operations)
    php artisan storage:link && \
    php artisan view:clear && \
    php artisan route:clear
"""

[deploy]
startCommand = """
    php artisan config:clear && \
    php artisan cache:clear && \
    php artisan config:cache && \
    php artisan route:cache && \
    php artisan view:cache && \
    php artisan migrate --force && \
    php artisan serve --host=0.0.0.0 --port=$PORT
"""
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never" 