[build]
builder = "nixpacks"
buildCommand = "composer install && npm install && npm run build"

[deploy]
startCommand = "php artisan migrate && php artisan serve"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never" 